/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import React from "react";
import {
  Alert,
  AlertProps,
  Box,
  Button,
  CollectionPreferences,
  Container,
  Header,
  Pagination,
  Select,
  SelectProps,
  SpaceBetween,
  Table,
  TableProps,
  TextFilter,
} from "@cloudscape-design/components";
import { useCollection } from "@cloudscape-design/collection-hooks";

import { EntitySchema } from "../../models";
import { getColumnDefinitions } from "../../resources/ItemTableConfig";
import { ErrorWithType } from "../../actions/ErrorHandlerHook";
import { updateParentsChildren, valueContainsKeyword } from "./TransferList.util";

/**
 * Prop with column definitions but never schema and schemaName
 */
interface PropsWithColumnDefinitions<E> {
  /**
   * Column definitions for the table display.
   * If the children records have a schema, this can be generated by calling `getColumnDefinitions` function
   */
  columnDefinitions: TableProps.ColumnDefinition<E>[];
  /**
   * The schema name of the child records. Used to load stored table preference and
   * deduce table column definitions if schema is provided
   */
  schemaName?: never;
  /**
   * The schema name of the child records
   */
  schema?: never;
}

/**
 * Prop with schema and schemaName but never column definitions
 */
interface PropsWithSchema {
  /**
   * Column definitions for the table display.
   * If the children records have a schema, this can be generated by calling `getColumnDefinitions` function
   */
  columnDefinitions?: never;
  /**
   * The schema name of the child records. Used to load stored table preference and
   * deduce table column definitions if schema is provided
   */
  schemaName: string;
  /**
   * The schema name of the child records
   */
  schema: EntitySchema;
}

// Union type that requires either columnDefinitions or both schema and schemaName
type PropsWithExclusiveSchemaOrColumnDefinitions<E> = PropsWithColumnDefinitions<E> | PropsWithSchema;

interface Notification extends Pick<AlertProps, "type"> {
  content: string | React.ReactNode;
}

/**
 * Props for the TransferList component.
 * @template P - The type of parent records
 * @template C - The type of child records
 */
export interface TransferListProps<P extends Record<string, unknown>, C extends Record<string, unknown>> {
  /**
   * The header content to display at the top of the component
   */
  readonly header: React.ReactNode;

  /**
   * Option to hide the dropdown filter in the tables
   */
  readonly hideDropdown?: boolean;

  readonly parent: {
    /**
     * An array of parent records to populate as the select dropdowns on the top of
     * the two tables of the transfer list.
     */
    readonly records: P[];
    /** The attribute of P to use as the label in the filter dropdown */
    readonly labelAttribute: keyof P;

    /** The attribute of P to use as the value in the filter dropdown */
    readonly valueAttribute: keyof P;

    /**
     * The multivalue-relationship attribute of the parent record
     */
    readonly multivalueRelationshipAttribute?: keyof P;
    /**
     * The initially selected parent in the select dropdown for Source table
     */
    readonly selectedValue: string;
  };

  readonly child: PropsWithExclusiveSchemaOrColumnDefinitions<C> & {
    /**
     * An array of children records to display and manipulate the two tables of the transfer list.
     */
    readonly records: C[];

    /**
     * The relationship attribute of the child record
     * @default parent.valueAttribute
     */
    readonly relationshipAttribute?: keyof C;

    /**
     * The attribute of C to retrieve the identifier and populate the multivalue-relationship attribute of parent
     */
    readonly valueAttribute: keyof C;

    /**
     * The default sort by column in both transfer tables
     */
    readonly sortByColumn?: keyof C & string;

    /**
     * Attributes to filter
     */
    readonly filteringAttributes?: string[];
  };

  /** Callback function when the operation is canceled */
  readonly onCancel?: () => void;

  /**
   * Callback function when changes are confirmed
   * @param data - Object containing updated parents and children arrays
   * @param data.parents - The array of parent records with updated relationships
   * @param data.children - The array of child records with updated assignments
   */
  readonly onConfirm?: (data: { parents: P[]; children: C[] }) => void | Promise<void>;

  /**
   * Callback function when changes are made
   * This is an alternative option to the onConfirm and onCancel callbacks, which are triggered by button actions
   * @param data - Object containing updated parents and children arrays
   * @param data.parents - The optional array of parent records with updated relationships
   * @param data.children - The array of child records with updated assignments
   */
  readonly onUpdate?: (data: { parents?: P[]; children: C[] }) => void;

  /**
   * Readonly mode. When true the buttons are all disabled
   */
  readonly readOnly?: boolean;

  readonly customLabels?: {
    /**
     * Override source transfer table header text
     */
    readonly sourceHeader?: string;

    /**
     * Override source transfer table button text
     */
    readonly sourceButtonText?: string;

    /**
     * Override target transfer table header text
     */
    readonly targetHeader?: string;

    /**
     * Override target transfer table button text
     */
    readonly targetButtonText?: string;
  };

  /**
   * Attribute to indicate whether data is being loaded/refreshed
   */
  readonly isLoading?: boolean;
}

/**
 * A UI component that manages parent-child relationships between records.
 *
 * @template P - The type of parent records that define the grouping options
 * @template C - The type of child records that can be transferred between groups
 * @param props - The component props
 * @returns A React component for managing transfers between lists
 */
function TransferList<P extends Record<string, unknown>, C extends Record<string, unknown>>({
  child,
  customLabels,
  header,
  hideDropdown,
  onCancel,
  onConfirm,
  onUpdate,
  parent,
  readOnly,
  isLoading,
}: TransferListProps<P, C>) {
  const [parents, setParents] = React.useState<P[]>([...parent.records]);
  const [children, setChildren] = React.useState<C[]>([...child.records]);
  // A state to record if the data is actually changed
  const [isDataChanged, setDataChanged] = React.useState<boolean>(false);
  const [isConfirming, setIsConfirming] = React.useState<boolean>(false);
  const [notification, setNotification] = React.useState<Notification>();

  React.useEffect(() => {
    setParents([...parent.records]);
  }, [parent.records]);

  React.useEffect(() => {
    setChildren([...child.records]);
  }, [child.records]);

  /**
   * Options for the source dropdown, derived from parent records
   */
  const sourceOptions: SelectProps.Options = React.useMemo(
    () =>
      Array.from(
        new Map(
          parent.records
            .filter((item: P) => item[parent.valueAttribute])
            .map((item: P) => [
              item[parent.valueAttribute],
              {
                label: String(item[parent.labelAttribute]),
                value: String(item[parent.valueAttribute]),
              },
            ])
        ).values()
      ),
    [parent.records, parent.valueAttribute, parent.labelAttribute]
  );

  // State for the source select dropdown selectedOption and value can be null
  // i.e. somehow no option matches the `parent.selectedValue` property value
  const [sourceSelectedOption, setSourceSelectedOption] = React.useState<SelectProps.Option | null>(
    sourceOptions.find((option: SelectProps.Option) => option.value === parent.selectedValue) ?? null
  );

  /**
   * The attribute in child records that stores the relationship to parent records
   * Falls back to using the parent's valueAttribute if not explicitly provided
   */
  const childRelationshipAttribute = child.relationshipAttribute ?? (parent.valueAttribute as keyof C);

  /**
   * Options for the target dropdown, derived from source options but excluding the currently selected source
   * Also always includes an "Unassigned" option
   */
  const targetOptions = React.useMemo(() => {
    return [...sourceOptions, { label: "Unassigned", value: undefined }].filter(
      (option: SelectProps.Option) => option.value === undefined || option.value !== sourceSelectedOption?.value
    );
  }, [sourceOptions, sourceSelectedOption]);

  // State for the target select dropdown selectedOption and value won't be null
  // as it can always fallback to "Unassigned"
  const [targetSelectedOption, setTargetSelectedOption] = React.useState<SelectProps.Option>(targetOptions[0]);

  React.useEffect(() => {
    // Change target selected option if it is the same as the source select dropdown
    if (targetSelectedOption.value === sourceSelectedOption?.value) {
      setTargetSelectedOption(targetOptions[0]);
    }
    // Auto select Unassigned if unassigned children available
    if (targetSelectedOption == null) {
      const unassignedOption = targetOptions.find((opt) => opt.value === undefined);
      if (unassignedOption) setTargetSelectedOption(unassignedOption);
    }
  }, [targetOptions, sourceSelectedOption, targetSelectedOption]);

  /**
   * Handler for removing items from the source (selected parent)
   * Memoized to prevent unnecessary re-renders
   */
  const removeFromSource = React.useCallback(
    (selectedChildren: C[]) => {
      const { updatedParents, updatedChildren } = updateParentsChildren<P, C>({
        action: "remove",
        parent,
        child,
        children,
        selectedChildren,
        parents,
      });
      setChildren(updatedChildren);
      setDataChanged(true);
      if (updatedParents) setParents(updatedParents);
      onUpdate?.({ parents: updatedParents, children: updatedChildren });
    },
    [parent, child, children, parents, onUpdate]
  );

  /**
   * Handler for adding items to the source (selected parent)
   * Memoized to prevent unnecessary re-renders
   */
  const addToSource = React.useCallback(
    (selectedChildren: C[]) => {
      const { updatedParents, updatedChildren } = updateParentsChildren<P, C>({
        action: "move",
        parent,
        child,
        children,
        selectedChildren,
        parents,
        targetParentId: sourceSelectedOption?.value,
      });
      setChildren(updatedChildren);
      setDataChanged(true);
      if (updatedParents) setParents(updatedParents);
      onUpdate?.({ parents: updatedParents, children: updatedChildren });
    },
    [parent, child, children, parents, sourceSelectedOption?.value, onUpdate]
  );

  const columnDefAndSchemaProps = child.columnDefinitions?.length
    ? ({ columnDefinitions: child.columnDefinitions } as PropsWithColumnDefinitions<C>)
    : ({ schema: child.schema, schemaName: child.schemaName } as PropsWithSchema);

  return (
    <Container header={header}>
      <SpaceBetween direction="vertical" size="l">
        <TransferListTable
          {...columnDefAndSchemaProps}
          action={{
            buttonText: customLabels?.sourceButtonText || "Remove from Source",
            onAction: removeFromSource,
          }}
          isLoading={isLoading}
          isConfirming={isConfirming}
          readOnly={readOnly}
          records={children}
          headerText={customLabels?.sourceHeader || "Source"}
          filter={{
            attribute: childRelationshipAttribute,
            selectOptions: sourceOptions,
            selectedOption: sourceSelectedOption,
            onOptionSelect: setSourceSelectedOption,
          }}
          hideDropdown={hideDropdown}
          sortByColumn={child.sortByColumn}
        />
        <TransferListTable
          {...columnDefAndSchemaProps}
          action={{
            buttonText: customLabels?.targetButtonText || "Add to Source",
            onAction: addToSource,
          }}
          isLoading={isLoading}
          isConfirming={isConfirming}
          readOnly={readOnly}
          records={children}
          headerText={customLabels?.targetHeader || "Target"}
          filter={{
            attribute: childRelationshipAttribute,
            selectOptions: targetOptions,
            selectedOption: targetSelectedOption,
            onOptionSelect: setTargetSelectedOption,
          }}
          hideDropdown={hideDropdown}
          sortByColumn={child.sortByColumn}
        />
        {notification ? (
          <Box>
            <Alert type={notification.type} dismissible onDismiss={() => setNotification(undefined)}>
              {notification.content}
            </Alert>
          </Box>
        ) : null}
        {onCancel && onConfirm ? (
          <Box float="right">
            <SpaceBetween direction="horizontal" size="xs">
              <Button
                variant="link"
                disabled={isLoading || isConfirming || readOnly}
                onClick={() => {
                  setDataChanged(false);
                  onCancel();
                }}
              >
                Cancel
              </Button>
              <Button
                variant="primary"
                loading={isConfirming}
                disabled={isLoading || isConfirming || !isDataChanged || readOnly}
                onClick={() => {
                  setIsConfirming(true);
                  return Promise.resolve(onConfirm({ parents, children }))
                    .then(() => {
                      setDataChanged(false);
                    })
                    .catch((e) => {
                      setNotification({
                        type: e instanceof ErrorWithType ? e.type : "error",
                        content: e instanceof Error ? e.message : "An unexpected error occurred",
                      });
                    })
                    .finally(() => setIsConfirming(false));
                }}
              >
                Confirm
              </Button>
            </SpaceBetween>
          </Box>
        ) : null}
      </SpaceBetween>
    </Container>
  );
}

/**
 * Props for the internal TransferListTable component.
 *
 * @template E - The type of elements in the records array
 */
interface TransferListTableProps<E> {
  /** The text to display in the table header */
  readonly headerText: string;

  /** Array of records to display in the table */
  readonly records: E[];

  /** Configuration for filtering the table data */
  readonly filter: {
    /** The attribute of E to filter on */
    readonly attribute: keyof E;

    /** Available options for the filter dropdown */
    readonly selectOptions: SelectProps.Options;

    /** Currently selected filter option */
    readonly selectedOption: SelectProps.Option | null;

    /** Callback when a filter option is selected */
    readonly onOptionSelect: (option: SelectProps.Option) => void;
  };

  /** Configuration for the action button */
  readonly action: {
    /** Text to display on the action button */
    buttonText: string;

    /** Callback when the action button is clicked */
    onAction: (selectedItems: E[]) => void;
  };
  /**
   * Option to hide the dropdown filter in the table
   */
  readonly hideDropdown?: boolean;

  /**
   * The default sort by column in the table
   */
  readonly sortByColumn?: string;

  /**
   * Attributes to filter
   */
  readonly filteringAttributes?: string[];

  /**
   * When true, all the buttons are disabled and Confirm button shows loading
   */
  readonly isConfirming?: boolean;

  /**
   * Readonly mode. When true the buttons are all disabled
   */
  readonly readOnly?: boolean;

  /**
   * When true, show a loading spinner instead of data
   */
  readonly isLoading?: boolean;
}

/**
 * Internal component that renders a table with filtering and selection capabilities.
 *
 * @template E - The type of elements in the records array
 * @param props - The component props
 * @returns A React component displaying a filterable, selectable table
 */
function TransferListTable<E extends Record<string, unknown>>(
  props: TransferListTableProps<E> & PropsWithExclusiveSchemaOrColumnDefinitions<E>
) {
  const { action, filter, headerText, hideDropdown, isConfirming, records, readOnly, sortByColumn, isLoading } = props;

  const columnDefinitions = React.useMemo(() => {
    const colDefProps = props.columnDefinitions?.length
      ? (props as PropsWithColumnDefinitions<E>)
      : (props as PropsWithSchema);
    return (
      colDefProps.columnDefinitions ??
      (getColumnDefinitions(colDefProps.schemaName, colDefProps.schema) as TableProps.ColumnDefinition<E>[])
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.columnDefinitions, props.schemaName, props.schema]);

  const filteringAttributes = React.useMemo(() => {
    if (props.filteringAttributes) return props.filteringAttributes;

    const colDefProps = props.columnDefinitions?.length
      ? (props as PropsWithColumnDefinitions<E>)
      : (props as PropsWithSchema);

    return !colDefProps.columnDefinitions
      ? colDefProps.schema.attributes
          .filter((attr) => !["relationship", "multivalue-relationship"].includes(attr.type))
          .map((attr) => attr.name)
      : undefined;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.filteringAttributes, props.schema]);

  const tablePreferenceLocalStorageKey = props.schemaName ? props.schemaName + "_table_prefs" : undefined;

  const [preferences, setPreferences] = React.useState(() => {
    const defaultPreferences = {
      pageSize: 10,
      visibleContent: columnDefinitions.map((column) => column.id || ""),
    };
    if (!tablePreferenceLocalStorageKey) {
      return defaultPreferences;
    }
    try {
      // Same local storage key naming as ItemTable so as to reuse the same preference
      return JSON.parse(localStorage.getItem(tablePreferenceLocalStorageKey) ?? "");
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
    } catch (e) {
      return defaultPreferences;
    }
  });

  React.useEffect(() => {
    if (!tablePreferenceLocalStorageKey) return;
    try {
      localStorage.setItem(tablePreferenceLocalStorageKey, JSON.stringify(preferences));
    } catch (e) {
      console.warn("Failed to save table preferences to localStorage", e);
    }
  }, [preferences, tablePreferenceLocalStorageKey]);

  const noData = (
    <Box margin={{ vertical: "xs" }} textAlign="center" color="inherit">
      <b>No data</b>
    </Box>
  );

  const { actions, items, collectionProps, filteredItemsCount, paginationProps, filterProps } = useCollection(records, {
    filtering: {
      empty: noData,
      noMatch: noData,
      filteringFunction: (item, filteringText) => {
        // First apply the dropdown filter
        const passesDropdownFilter = filter.selectedOption?.value
          ? item[filter.attribute] === filter.selectedOption.value
          : item[filter.attribute] == null; // should show only unassigned items when no option is selected

        // If filteringText is empty, just return the dropdown filter result, otherwise both the dropdown filter and filteringText
        return filteringText
          ? passesDropdownFilter && valueContainsKeyword(item, filteringText, filteringAttributes)
          : passesDropdownFilter;
      },
    },
    pagination: { pageSize: preferences.pageSize },
    sorting:
      columnDefinitions.length > 0
        ? {
            defaultState: {
              sortingColumn:
                (sortByColumn && columnDefinitions.find((def) => def.id === sortByColumn)) || columnDefinitions[0],
            },
          }
        : undefined,
  });

  const [selectedItems, selectItems] = React.useState<E[]>([]);

  // Clear selection and filter text if the dropdown selected option change
  React.useEffect(() => {
    selectItems([]);
    actions.setFiltering("");
    // add actions to the dependency result in the callback get called on each item selection
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filter.selectedOption]);

  // Clear selection and filter text if the dropdown options no longer have the selected one
  React.useEffect(() => {
    const selectedValue = filter.selectedOption?.value;
    if (selectedValue && !filter.selectOptions.find((option) => option.value === selectedValue)) {
      selectItems([]);
      actions.setFiltering("");
    }
    // add actions to the dependency result in the callback get called on each item selection
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filter.selectOptions, records]);

  const counter = selectedItems.length ? `(${selectedItems.length}/${filteredItemsCount})` : `(${filteredItemsCount})`;

  const visibleColumnDefinitions = React.useMemo(() => {
    if (!preferences.visibleContent) {
      return columnDefinitions;
    }
    return columnDefinitions.filter((column) =>
      preferences.visibleContent ? preferences.visibleContent.includes(column.id ?? "") : true
    );
  }, [columnDefinitions, preferences.visibleContent]);

  return (
    <Table
      {...collectionProps}
      header={
        <Header
          actions={
            <Button
              disabled={isLoading || isConfirming || readOnly}
              variant="normal"
              onClick={() => {
                action.onAction(selectedItems);
                selectItems([]);
              }}
            >
              {action.buttonText}
            </Button>
          }
          counter={counter}
        >
          {headerText}
        </Header>
      }
      loading={isLoading}
      items={items}
      columnDefinitions={visibleColumnDefinitions}
      isItemDisabled={() => !!readOnly}
      filter={
        <SpaceBetween direction="vertical" size="xs">
          {hideDropdown ? null : (
            <Box margin={{ top: "m", bottom: "m" }}>
              <Select
                options={filter.selectOptions}
                selectedOption={filter.selectedOption}
                onChange={(e) => {
                  filter.onOptionSelect(e.detail.selectedOption);
                }}
              />
            </Box>
          )}
          <TextFilter
            {...filterProps}
            filteringPlaceholder={"Search by any field"}
            countText={`${filteredItemsCount} matches`}
          />
        </SpaceBetween>
      }
      selectionType="multi"
      selectedItems={selectedItems}
      onSelectionChange={(e) => selectItems(e.detail.selectedItems)}
      onRowClick={(e) => selectItems([e.detail.item])}
      pagination={<Pagination {...paginationProps} />}
      preferences={
        <CollectionPreferences
          title="Preferences"
          confirmLabel="Confirm"
          cancelLabel="Cancel"
          preferences={preferences}
          onConfirm={({ detail }) => setPreferences(detail)}
          pageSizePreference={{
            title: "Page size",
            options: [
              { value: 10, label: "10 items" },
              { value: 20, label: "20 items" },
              { value: 50, label: "50 items" },
            ],
          }}
          visibleContentPreference={{
            title: "Select visible columns",
            options: [
              {
                label: "Columns",
                options: columnDefinitions.map((column) => ({
                  id: column.id ?? "",
                  label: String(column.header),
                })),
              },
            ],
          }}
          wrapLinesPreference={{
            label: "Wrap lines",
            description: "Check to see all the text and wrap the lines",
          }}
        />
      }
    />
  );
}

/**
 * A UI component that manages parent-child relationships between records.
 *
 * This component renders two tables:
 * - Source table: Shows child records assigned to the selected parent
 * - Target table: Shows child records assigned to other parents or unassigned
 *
 * Users can transfer items between tables to update relationships. The component
 * maintains both the parent-child relationships and updates any multivalue relationship
 * attributes in the parent records.
 *
 * Memoized for better performance.
 *
 * @template P - The type of parent records that define the grouping options
 * @template C - The type of child records that can be transferred between groups
 */
export default React.memo(TransferList) as typeof TransferList;
