[tool.poetry]
name = "cloud-migration-factory-on-aws"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
simplejson = "^3.19.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"